### ISSUE TITLE
Can't load XGBoostModel on Java 11

### ISSUE THREAD

**Issue by rculbertson** [spotify/zoltar#181]
`XGBoostLoader.create` throws a `ClassCastException` on Java 11. This because [libField.get()](https://github.com/spotify/zoltar/blob/v0.5.3/zoltar-xgboost/src/main/java/ml/dmlc/xgboost4j/java/GompLoader.java#L67) returns a HashSet instead of a Vector.

```
java.lang.ClassCastException: class java.util.HashSet cannot be cast to class java.util.Vector (java.util.HashSet and java.util.Vector are in module java.base of loader 'bootstrap')
	at ml.dmlc.xgboost4j.java.GompLoader.getLoadedLibraries(GompLoader.java:67)
	at ml.dmlc.xgboost4j.java.GompLoader.load(GompLoader.java:47)
	at ml.dmlc.xgboost4j.java.GompLoader.start(GompLoader.java:81)
	at com.spotify.zoltar.xgboost.XGBoostModel.create(XGBoostModel.java:61)
	at com.spotify.zoltar.xgboost.XGBoostModel.create(XGBoostModel.java:51)
	at com.spotify.zoltar.xgboost.XGBoostLoader.lambda$create$0(XGBoostLoader.java:44)
	at com.spotify.zoltar.ModelLoader.lambda$null$0(ModelLoader.java:59)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mattnworb** [comment]
@rculbertson can this be closed now? sounds like the PR above fixed things

**Comment by rculbertson** [comment]
@mattnworb Yes, this can be closed.
